[package]
name = "repose-unlockctl"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "repose-unlockctl"
path = "src/main.rs"

[dependencies]
libc = "0.2"
plist = { version = "~1.10.1", features = ["enable_unstable_features_that_may_break_with_minor_version_bumps"] }
repose-authdb-policy = { path = "../repose-authdb-policy" }
sha2 = "0.10"

[build-dependencies]
cc = "1"
