// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum NativeCompanionCapability {
  ready,
  associationNotConfigured,
  bluetoothUnavailable,
  secureHardwareUnavailable,
  backgroundExecutionUnavailable,
  unsupportedPlatform,
  nativeBridgeUnavailable,
}

enum NativeCompanionPlatform { android, ios }

enum NativeCalibrationStep { near, far }

enum NativeCalibrationPhase {
  idle,
  collectingNear,
  collectingFar,
  complete,
  overlapRejected,
  unavailable,
  failed,
}

class NativePairingSession {
  NativePairingSession({
    required this.sessionId,
    required this.deviceName,
    required this.expiresAtEpochMillis,
  });

  String sessionId;

  String deviceName;

  int expiresAtEpochMillis;

  List<Object?> _toList() {
    return <Object?>[sessionId, deviceName, expiresAtEpochMillis];
  }

  Object encode() {
    return _toList();
  }

  static NativePairingSession decode(Object result) {
    result as List<Object?>;
    return NativePairingSession(
      sessionId: result[0]! as String,
      deviceName: result[1]! as String,
      expiresAtEpochMillis: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePairingSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(deviceName, other.deviceName) &&
        _deepEquals(expiresAtEpochMillis, other.expiresAtEpochMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePairingSession(sessionId: $sessionId, deviceName: $deviceName, expiresAtEpochMillis: $expiresAtEpochMillis)';
  }
}

class NativePairedDevice {
  NativePairedDevice({
    required this.id,
    required this.displayName,
    required this.platform,
  });

  String id;

  String displayName;

  NativeCompanionPlatform platform;

  List<Object?> _toList() {
    return <Object?>[id, displayName, platform];
  }

  Object encode() {
    return _toList();
  }

  static NativePairedDevice decode(Object result) {
    result as List<Object?>;
    return NativePairedDevice(
      id: result[0]! as String,
      displayName: result[1]! as String,
      platform: result[2]! as NativeCompanionPlatform,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePairedDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(displayName, other.displayName) &&
        _deepEquals(platform, other.platform);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePairedDevice(id: $id, displayName: $displayName, platform: $platform)';
  }
}

class NativeCalibrationSnapshot {
  NativeCalibrationSnapshot({required this.phase});

  NativeCalibrationPhase phase;

  List<Object?> _toList() {
    return <Object?>[phase];
  }

  Object encode() {
    return _toList();
  }

  static NativeCalibrationSnapshot decode(Object result) {
    result as List<Object?>;
    return NativeCalibrationSnapshot(
      phase: result[0]! as NativeCalibrationPhase,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCalibrationSnapshot ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(phase, other.phase);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCalibrationSnapshot(phase: $phase)';
  }
}

class NativeUnlockSnapshot {
  NativeUnlockSnapshot({
    required this.capability,
    required this.devices,
    required this.calibration,
    this.pendingPairing,
  });

  NativeCompanionCapability capability;

  List<NativePairedDevice> devices;

  NativeCalibrationSnapshot calibration;

  NativePairingSession? pendingPairing;

  List<Object?> _toList() {
    return <Object?>[capability, devices, calibration, pendingPairing];
  }

  Object encode() {
    return _toList();
  }

  static NativeUnlockSnapshot decode(Object result) {
    result as List<Object?>;
    return NativeUnlockSnapshot(
      capability: result[0]! as NativeCompanionCapability,
      devices: (result[1]! as List<Object?>).cast<NativePairedDevice>(),
      calibration: result[2]! as NativeCalibrationSnapshot,
      pendingPairing: result[3] as NativePairingSession?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeUnlockSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(capability, other.capability) &&
        _deepEquals(devices, other.devices) &&
        _deepEquals(calibration, other.calibration) &&
        _deepEquals(pendingPairing, other.pendingPairing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeUnlockSnapshot(capability: $capability, devices: $devices, calibration: $calibration, pendingPairing: $pendingPairing)';
  }
}

class NativeDiagnostics {
  NativeDiagnostics({required this.summary});

  String summary;

  List<Object?> _toList() {
    return <Object?>[summary];
  }

  Object encode() {
    return _toList();
  }

  static NativeDiagnostics decode(Object result) {
    result as List<Object?>;
    return NativeDiagnostics(summary: result[0]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDiagnostics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(summary, other.summary);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDiagnostics(summary: $summary)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeCompanionCapability) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is NativeCompanionPlatform) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NativeCalibrationStep) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is NativeCalibrationPhase) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is NativePairingSession) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is NativePairedDevice) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is NativeCalibrationSnapshot) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is NativeUnlockSnapshot) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NativeDiagnostics) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCompanionCapability.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCompanionPlatform.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCalibrationStep.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCalibrationPhase.values[value];
      case 133:
        return NativePairingSession.decode(readValue(buffer)!);
      case 134:
        return NativePairedDevice.decode(readValue(buffer)!);
      case 135:
        return NativeCalibrationSnapshot.decode(readValue(buffer)!);
      case 136:
        return NativeUnlockSnapshot.decode(readValue(buffer)!);
      case 137:
        return NativeDiagnostics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ReposeUnlockHostApi {
  /// Constructor for [ReposeUnlockHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ReposeUnlockHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeUnlockSnapshot> getSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.getSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeUnlockSnapshot;
  }

  Future<void> requestCompanionAssociation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.requestCompanionAssociation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<NativePairingSession> beginPairing(String qrPayload) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.beginPairing$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[qrPayload],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativePairingSession;
  }

  Future<void> confirmPairing(String sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.confirmPairing$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> startCalibration() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.startCalibration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> submitCalibrationStep(NativeCalibrationStep step) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.submitCalibrationStep$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[step],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> revokeDevice(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.revokeDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<NativeDiagnostics> getDiagnostics() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.repose_unlock_native.ReposeUnlockHostApi.getDiagnostics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeDiagnostics;
  }
}
