// repose-pair-v2 — the Mac side's arithmetic.
//
// Protocol: docs/plans/2026-09-11-pairing-v2.md
//
//   M1  Mac  -> phone : PK_M(65)
//   P1  phone-> Mac   : PK_P(65) ‖ Cp(32)      Cp = SHA256(COMMIT‖PK_M‖PK_P‖Np)
//   M2  Mac  -> phone : Nm(16)
//   P2  phone-> Mac   : Np(16)                 Mac verifies Cp here
//
//   sasHash = SHA256(SAS‖PK_M‖PK_P‖Nm‖Np)
//   digits  = int_be(sasHash[0..4]) mod 1e6
//   K       = HKDF(salt: sasHash, ikm: ECDH_x, info: KDF, 32)
//
// The commitment is the whole protocol. The phone fixes Np before it can see
// Nm, so a man in the middle cannot pick his own nonce after seeing the other
// side's to make both screens agree. Cp covers PK_M as well, so one commitment
// cannot be replayed at a different Mac.
//
// Using sasHash as the HKDF salt means that even on the ~1-in-a-million chance
// the six digits collide, the two halves of a MITM derive different keys and the
// relay still does not join up.
//
// Build: swiftc -O -o pair-crypto pair-crypto.swift
// Run:   ./pair-crypto --self-test

import CryptoKit
import Foundation

let COMMIT_LABEL = "repose-pair-v2 commit"
let SAS_LABEL = "repose-pair-v2 sas"
let KDF_LABEL = "repose-pair-v2 presence-key"

func hexDecode(_ s: String) -> Data? {
    guard s.count % 2 == 0, !s.isEmpty else { return nil }
    var out = Data(capacity: s.count / 2)
    var i = s.startIndex
    while i < s.endIndex {
        let j = s.index(i, offsetBy: 2)
        guard let b = UInt8(s[i..<j], radix: 16) else { return nil }
        out.append(b)
        i = j
    }
    return out
}

func hex(_ d: Data) -> String { d.map { String(format: "%02x", $0) }.joined() }

func ascii(_ s: String) -> Data { Data(s.utf8) }

// MARK: - the four values everything else is built from

func commitment(pkM: Data, pkP: Data, np: Data) -> Data {
    Data(SHA256.hash(data: ascii(COMMIT_LABEL) + pkM + pkP + np))
}

func sasHash(pkM: Data, pkP: Data, nm: Data, np: Data) -> Data {
    Data(SHA256.hash(data: ascii(SAS_LABEL) + pkM + pkP + nm + np))
}

/// Six digits, zero padded. Short on purpose: a human has to read it off two
/// screens and compare, and a longer string gets compared less carefully.
func sasDigits(_ hash: Data) -> String {
    let first4 = hash.prefix(4)
    let n = first4.reduce(UInt32(0)) { ($0 << 8) | UInt32($1) }
    return String(format: "%06d", n % 1_000_000)
}

/// HKDF-SHA256, salted with the transcript hash.
func deriveKey(ecdhX: Data, salt: Data) -> Data {
    let prk = HMAC<SHA256>.authenticationCode(for: ecdhX, using: SymmetricKey(data: salt))
    let okm = HMAC<SHA256>.authenticationCode(
        for: ascii(KDF_LABEL) + Data([0x01]),
        using: SymmetricKey(data: Data(prk)))
    return Data(okm)
}

/// The X coordinate of the shared point, 32 bytes with leading zeros kept.
///
/// CryptoKit's sharedSecretFromKeyAgreement is exactly that, which is the
/// definition the other side has to match -- a shared secret trimmed to its
/// significant bytes would agree with OpenSSL only when X happens not to start
/// with a zero, i.e. 255 times out of 256.
func ecdhX(privateScalar: Data, peerPublic: Data) throws -> Data {
    let sk = try P256.KeyAgreement.PrivateKey(rawRepresentation: privateScalar)
    let pk = try P256.KeyAgreement.PublicKey(x963Representation: peerPublic)
    let shared = try sk.sharedSecretFromKeyAgreement(with: pk)
    return shared.withUnsafeBytes { Data($0) }
}

/// Reject a peer key before touching it. CryptoKit's x963 initializer already
/// refuses points that are not on the curve, and refusing loudly here keeps that
/// from looking like a transport error later.
func parsePeerKey(_ d: Data) -> Data? {
    guard d.count == 65, d.first == 0x04 else { return nil }
    return (try? P256.KeyAgreement.PublicKey(x963Representation: d)) != nil ? d : nil
}

// MARK: - self test

/// Generated by tools/ble-spike/mac/pair-vectors.sh, which uses OpenSSL and
/// shares no code with this file or with the Kotlin side. Checking Swift against
/// numbers Swift produced would prove only that it is self-consistent; both
/// implementations being wrong the same way would sail through that.
struct Vec {
    static let skM = "b96e0676189db5cb28470e4dca48941385603d5e627726997fb97321746e69f9"
    static let skP = "e6c595364232f20b66876d41be23313ae40b255668757b3c06878364c3c7c0b2"
    static let pkM = "04ceeac1a625c3039e5e3176362e2b257461c66a8b3a5b23dbe67424c84b3f1202f34dd8c37e726e0474d28ff984c6fad4d3158baae761a1cfa50d3575d4d2af21"
    static let pkP = "04bba0ac866c040dee63395dc7ea9cd2ae65df7475c35295da07264de36a85dcc78f30b930a1af3147ac63a0d902593e53a78f7c9ab8773670562f50afea4bf035"
    static let nm = "000102030405060708090a0b0c0d0e0f"
    static let np = "f0e0d0c0b0a090807060504030201000"
    static let commit = "7161008840f0d9173b7c81381c9e5d81216c004373e08bbd597bdea5fd7018d0"
    static let sasHash = "a25de9292840328d5c634e856328c8251561f688f61c960ce05641e4add8aa46"
    static let digits = "063529"
    static let ecdhX = "8264224d7eb11f8f5240fe1b94a14c7202a9c493cdfc5fd406f6a46d681f6f94"
    static let key = "d4cdf8ede653c929321d134fea6e4382bcb1a02a37401392316d60a90ff532ee"
}

func check(_ name: String, _ got: String, _ want: String, _ failures: inout Int) {
    if got == want {
        print("  ok   \(name)")
    } else {
        print("  FAIL \(name)\n       got  \(got)\n       want \(want)")
        failures += 1
    }
}

func selfTest() -> Int32 {
    var f = 0
    let pkM = hexDecode(Vec.pkM)!, pkP = hexDecode(Vec.pkP)!
    let nm = hexDecode(Vec.nm)!, np = hexDecode(Vec.np)!

    check("commitment", hex(commitment(pkM: pkM, pkP: pkP, np: np)), Vec.commit, &f)

    let sh = sasHash(pkM: pkM, pkP: pkP, nm: nm, np: np)
    check("transcript hash", hex(sh), Vec.sasHash, &f)
    check("six digits", sasDigits(sh), Vec.digits, &f)

    // Both directions of the ECDH must land on the same X, or the two sides
    // derive different keys and the only symptom is a phone that never verifies.
    do {
        let xm = try ecdhX(privateScalar: hexDecode(Vec.skM)!, peerPublic: pkP)
        let xp = try ecdhX(privateScalar: hexDecode(Vec.skP)!, peerPublic: pkM)
        check("ECDH x (mac side)", hex(xm), Vec.ecdhX, &f)
        check("ECDH x (phone side)", hex(xp), Vec.ecdhX, &f)
        check("derived key", hex(deriveKey(ecdhX: xm, salt: sh)), Vec.key, &f)
    } catch {
        print("  FAIL ECDH threw: \(error)")
        f += 1
    }

    // A commitment that does not match its nonce must be refused. This is the
    // step a man in the middle has to beat, so it gets its own check rather than
    // being implied by the happy path.
    var tampered = np
    tampered[tampered.startIndex] ^= 0x01
    if hex(commitment(pkM: pkM, pkP: pkP, np: tampered)) == Vec.commit {
        print("  FAIL a different nonce produced the same commitment")
        f += 1
    } else {
        print("  ok   a different nonce breaks the commitment")
    }

    // Changing either public key must change the digits, or the SAS is not
    // actually binding the keys it is supposed to authenticate.
    var otherKey = pkM
    otherKey[otherKey.startIndex + 1] ^= 0x01
    let shifted = sasHash(pkM: otherKey, pkP: pkP, nm: nm, np: np)
    if sasDigits(shifted) == Vec.digits {
        print("  FAIL a substituted public key produced the same digits")
        f += 1
    } else {
        print("  ok   a substituted public key changes the digits")
    }

    // Garbage peer keys are refused rather than parsed.
    for bad in ["", "04", String(repeating: "00", count: 65)] {
        if parsePeerKey(hexDecode(bad) ?? Data()) != nil {
            print("  FAIL accepted a malformed peer key: \(bad.prefix(8))")
            f += 1
        }
    }
    print("  ok   malformed peer keys are refused")

    print(f == 0 ? "\nself-test passed" : "\n\(f) failed")
    return f == 0 ? 0 : 1
}

// MARK: - main

let args = Array(CommandLine.arguments.dropFirst())
if args.first == "--self-test" {
    exit(selfTest())
}
FileHandle.standardError.write("usage: pair-crypto --self-test\n".data(using: .utf8)!)
exit(64)
